name: CI
on: [push, pull_request]
env:
  HUSKY: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run tsc:ci
      - run: bun run fmt:ci
      - run: bun run lint:ci
      - run: bun run test
