name: CI
on: [push, pull_request]
env:
  HUSKY: 0
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run tsc:ci
      - run: bun run fmt:ci
      - run: bun run lint:ci
  bun_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.1.26', '1.1.25', '1.1.24', '1.1.23']
    name: Bun ${{ matrix.version }} tests
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.version }}
      - run: bun install --frozen-lockfile
      - run: bun run test
  node_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20, 22]
    name: Node ${{ matrix.version }} tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: npm install -g yarn
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run test
